import cmath
import json
import math
from pathlib import Path


gauge_data = json.loads(Path("gauge_holonomy_results.json").read_text())

p = 2
core_complement_generator = 1
core_meridian = p * core_complement_generator


def character(phase, integer):
    return cmath.exp(1j * phase * integer)


ambient_torsion_phase = math.pi
ambient_on_generator = character(ambient_torsion_phase, core_complement_generator)
ambient_on_meridian = character(ambient_torsion_phase, core_meridian)

square_root_phases = [math.pi / 2.0, -math.pi / 2.0]
square_root_branches = []
for phase in square_root_phases:
    on_generator = character(phase, core_complement_generator)
    on_meridian = character(phase, core_meridian)
    square_root_branches.append(
        {
            "phase_on_generator_over_pi": phase / math.pi,
            "holonomy_on_generator": [on_generator.real, on_generator.imag],
            "square_on_generator": [
                (on_generator**2).real,
                (on_generator**2).imag,
            ],
            "holonomy_on_core_meridian": [on_meridian.real, on_meridian.imag],
            "descends_across_core": abs(on_meridian - 1.0) < 1e-12,
        }
    )

quarter_branch = next(
    row for row in gauge_data["beta_sweep"] if abs(row["beta"] - 0.25) < 1e-12
)
gauge_holonomies = [
    cmath.exp(1j * math.pi * quarter_branch["theta_plus_over_pi"]),
    cmath.exp(1j * math.pi * quarter_branch["theta_minus_over_pi"]),
]

meridian_fermion_phase = math.pi
majorana_pair_charge = 2
forced_pair_phase_change = majorana_pair_charge * meridian_fermion_phase
forced_vortex_winding = int(round(forced_pair_phase_change / (2.0 * math.pi)))
forced_mod2_index = forced_vortex_winding % 2

spin_holonomy_on_core = -1
ambient_torsion_holonomy_on_core = -1
candidate_core_holonomy = spin_holonomy_on_core * ambient_torsion_holonomy_on_core

results = {
    "status": "torsion_square_root_forces_pi_meridian_flux_and_odd_vortex_core_gluing_open",
    "date": "2026-08-03",
    "topology": {
        "ambient": "RP3=L(2,1)",
        "core": "generator gamma of H1(RP3;Z)=Z2",
        "core_complement": "solid torus with H1=Z generated by y",
        "filling_relation": "mu_core=2*y",
        "quotient_map": "Z -> Z2, n -> n mod 2",
        "kernel": "2Z generated by the core meridian",
    },
    "smooth_ambient_torsion_line": {
        "character_on_y": [ambient_on_generator.real, ambient_on_generator.imag],
        "character_on_mu_core": [ambient_on_meridian.real, ambient_on_meridian.imag],
        "consequence": (
            "The ordinary Z2 flat line is locally trivial around the core meridian and does not "
            "by itself force an odd vortex."
        ),
    },
    "square_root_defect": {
        "equation": "chi_root(y)^2=chi_Z2(y)=-1",
        "solutions": "chi_root(y)=+i or -i",
        "branches": square_root_branches,
        "meridian_result": "chi_root(mu)=chi_root(2y)=-1",
        "interpretation": (
            "The square root exists on the solid-torus complement but cannot extend through the "
            "core. It is a discrete Z4/quarter-holonomy defect with pi meridian flux."
        ),
    },
    "existing_gauge_holonomy_match": {
        "beta": quarter_branch["beta"],
        "theta_plus_over_pi": quarter_branch["theta_plus_over_pi"],
        "theta_minus_over_pi": quarter_branch["theta_minus_over_pi"],
        "holonomies": [[value.real, value.imag] for value in gauge_holonomies],
        "squares": [[(value**2).real, (value**2).imag] for value in gauge_holonomies],
        "match": (
            "The beta=1/4 charge doublet is exactly the conjugate pair -i,+i whose squares are "
            "the nontrivial Z2 holonomy."
        ),
    },
    "forced_majorana_vortex": {
        "fermion_meridian_phase": meridian_fermion_phase,
        "pair_charge": majorana_pair_charge,
        "finite_energy_rule": "Delta arg(Delta)=q_pair * integral(A)",
        "pair_phase_change": forced_pair_phase_change,
        "vortex_winding": forced_vortex_winding,
        "mod_two_index": forced_mod2_index,
        "interpretation": (
            "A charge-two Majorana pairing channel around a pi-flux defect must wind once. The odd "
            "winding required by the previous defect audit is therefore discrete rather than fitted."
        ),
    },
    "longitudinal_consistency_candidate": {
        "spin_holonomy_on_gamma": spin_holonomy_on_core,
        "ambient_Z2_holonomy_on_gamma": ambient_torsion_holonomy_on_core,
        "product": candidate_core_holonomy,
        "status": "algebraically_periodic_but_core_gluing_of_the_square_root_line_not_yet_derived",
    },
    "parameter_audit": {
        "continuous_parameter_added": False,
        "discrete_choice": "orientation/conjugation branch +i versus -i",
        "new_structure": "a singular square root of the ambient torsion line on RP3 minus gamma",
        "relation_to_existing_data": "matches the already audited beta=1/4 gauge-holonomy doublet",
    },
    "theory_effect": {
        "odd_winding": "upgraded_from_free_defect_assumption_to_discrete_square_root_torsion_candidate",
        "rank_one_defect_route": "strengthened_but_not_closed",
        "rank_23": "conditional",
        "remaining_gate": (
            "derive the square-root defect line and its core boundary condition from the S2T action, "
            "then prove the unique transverse mode carries the periodic longitudinal line"
        ),
    },
    "verdict": (
        "The smooth Z2 flat line alone cannot force an odd local vortex because the core meridian is "
        "twice the complement generator. However, its square root on the complement is canonical up "
        "to conjugation: chi(y)=+/-i. This quarter-holonomy branch has meridian holonomy -1, matches "
        "the existing beta=1/4 gauge doublet, and forces unit winding in a charge-two Majorana pair "
        "field. It supplies a non-fitted origin for the odd defect sector, while the extension of the "
        "resulting zero mode along the core remains to be proved."
    ),
}

assert abs(ambient_on_generator + 1.0) < 1e-12
assert abs(ambient_on_meridian - 1.0) < 1e-12
assert all(abs(complex(*branch["square_on_generator"]) + 1.0) < 1e-12 for branch in square_root_branches)
assert all(abs(complex(*branch["holonomy_on_core_meridian"]) + 1.0) < 1e-12 for branch in square_root_branches)
assert all(abs(value**2 + 1.0) < 1e-12 for value in gauge_holonomies)
assert forced_vortex_winding == 1
assert forced_mod2_index == 1
assert candidate_core_holonomy == 1

Path("s2t_neutrino_torsion_square_root_defect_results.json").write_text(
    json.dumps(results, indent=2, ensure_ascii=False) + "\n"
)
print(
    json.dumps(
        {
            "status": results["status"],
            "ambient_meridian_holonomy": results["smooth_ambient_torsion_line"]["character_on_mu_core"],
            "square_root_meridian_holonomy": square_root_branches[0]["holonomy_on_core_meridian"],
            "gauge_beta": quarter_branch["beta"],
            "forced_vortex_winding": forced_vortex_winding,
            "mod_two_index": forced_mod2_index,
        },
        indent=2,
        ensure_ascii=False,
    )
)