#!/usr/bin/env python3
"""Exact audit of the shifted-supercurvature cubic projection."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import sympy as sp


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "s2t/results/s2t_v8_baryon_spacetime_supercurvature_cubic_projection_admission_gate_results.json"
sys.path.insert(0, str(ROOT))

from s2t.proofdsl.examples.version8_full_noise_trace_frame import (  # noqa: E402
    full_noise_frame,
)


def main() -> None:
    m, t = sp.symbols("m t", real=True)
    frame = list(full_noise_frame())
    identity = sp.eye(21)
    grading = sp.diag(*([1] * 11 + [-1] * 10))
    centered = [
        sp.ImmutableMatrix(item - sp.trace(item) * identity / 21) for item in frame
    ]

    # The same exact ray used by the preceding coefficient no-go.
    ray = sp.ImmutableMatrix(centered[0] + centered[40])
    q2 = sp.expand(sp.trace(ray**2))
    q3 = sp.expand(sp.trace(ray**3))
    q4 = sp.expand(sp.trace(ray**4))

    z = t * ray
    curvature = sp.ImmutableMatrix(m * z + z**2)
    shifted_curvature = sp.ImmutableMatrix(
        (m * identity / 2 + z) ** 2 - (m * identity / 2) ** 2
    )
    action = sp.factor(sp.trace(curvature**2))
    expanded_action = sp.expand(action)

    alpha = sp.expand(m**2)
    lambda_3 = sp.expand(2 * m)
    beta = sp.Integer(1)
    shape_ratio = sp.cancel(lambda_3**2 / (alpha * beta))

    first = sp.factor(sp.diff(expanded_action, t))
    radial_quadratic = sp.Poly(first / (2 * t), t)
    stationary_discriminant = sp.factor(sp.discriminant(radial_quadratic.as_expr(), t))
    origin_hessian = sp.diff(expanded_action, t, 2).subs(t, 0)

    # A central background cannot be generated by the centered frame itself.
    central_background_trace = sp.trace(m * identity / 2)
    central_background_parity_defect = sp.ImmutableMatrix(
        grading * (m * identity / 2) + (m * identity / 2) * grading
    )
    centered_traces = [sp.trace(item) for item in centered]

    assert (q2, q3, q4) == (38, -3, 134)
    assert curvature == shifted_curvature
    assert expanded_action == 38 * m**2 * t**2 - 6 * m * t**3 + 134 * t**4
    assert (alpha, lambda_3, beta, shape_ratio) == (m**2, 2 * m, 1, 4)
    assert first == 2 * t * (38 * m**2 - 9 * m * t + 268 * t**2)
    assert stationary_discriminant == -40655 * m**2
    assert origin_hessian == 76 * m**2
    assert all(value == 0 for value in centered_traces)
    assert central_background_trace == sp.Rational(21, 2) * m
    assert central_background_parity_defect == m * grading

    exact_objects = [
        q2,
        q3,
        q4,
        *curvature,
        action,
        expanded_action,
        alpha,
        lambda_3,
        beta,
        shape_ratio,
        first,
        stationary_discriminant,
        origin_hessian,
        central_background_trace,
        *central_background_parity_defect,
        *centered_traces,
    ]
    assert not any(
        atom.is_Float
        for obj in exact_objects
        for atom in sp.preorder_traversal(obj)
    )

    result = {
        "date": "2026-08-30",
        "gate": "version8_baryon_spacetime_supercurvature_cubic_projection_admission_gate",
        "field": "Q(m,t)",
        "shifted_supercurvature": {
            "central_background": "M=(m/2)I_21",
            "definition": "R_m(Z)=(M+Z)^2-M^2=mZ+Z^2",
            "gauge_covariant_under_conjugation": True,
            "single_positive_norm": "Tr(R_m(Z)^2)",
        },
        "exact_ray": {
            "definition": "Z=t(Fhat_0+Fhat_40)",
            "Tr_A2": str(q2),
            "Tr_A3": str(q3),
            "Tr_A4": str(q4),
            "action": str(expanded_action),
        },
        "coefficient_shape": {
            "alpha": str(alpha),
            "lambda_3": str(lambda_3),
            "beta": str(beta),
            "lambda_3_squared_over_alpha_beta": str(shape_ratio),
            "cubic_projection_on_trace_tensor": "2m d_abc",
            "third_variation": "12m d_abc",
        },
        "radial_test": {
            "derivative": str(first),
            "nonzero_stationary_discriminant": str(stationary_discriminant),
            "origin_hessian": str(origin_hessian),
            "nonzero_stationary_point_for_real_nonzero_m": False,
        },
        "boundary": {
            "centered_frame_contains_central_background": False,
            "central_background_trace": str(central_background_trace),
            "central_background_odd_parity_defect": "Gamma M+M Gamma=m Gamma",
            "nonzero_central_background_is_odd": False,
            "full_42_frame_has_one_homogeneous_finite_parity": False,
            "background_scale_m_derived_by_current_parent": False,
            "spacetime_form_degree_and_hodge_trace_constructed": False,
            "absolute_lambda_3_derived": False,
        },
        "verdict": {
            "single_curvature_norm_generates_quadratic_cubic_quartic": True,
            "dimensionless_shape_ratio_fixed": True,
            "algebraic_moment_map_shape_admitted": True,
            "genuine_graded_supercurvature_realization_admitted": False,
            "physical_baryon_parent_closed": False,
            "next_gate": "noncentral_odd_dirac_background_projection_classification",
        },
    }

    text = json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    OUTPUT.write_text(text, encoding="utf-8")
    print(OUTPUT)
    print(hashlib.sha256(text.encode()).hexdigest())


if __name__ == "__main__":
    main()