#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
import sympy as sp
from s2t.proofdsl.examples.version10_cell_birth_four_volume_nonequilibrium_bath_continuum_dispersion_cell_geometry_typed_embedding import SPEC,build_certificate
from s2t.proofdsl.gates import verify_gate
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/"s2t/results/s2t_v10_cell_birth_four_volume_nonequilibrium_bath_continuum_dispersion_cell_geometry_typed_embedding_gate_results.json"
def main():
 v=verify_gate(SPEC);c=build_certificate();a=sp.Rational(24,121);xstar=(sp.exp(a)-1)/(2-sp.exp(a));Sstar=-sp.log(xstar);Slocked=sp.Rational(13703599917352236,10**14);xlocked=sp.exp(-Slocked);ulocked=sp.Rational(121,24)*sp.log((1+2*xlocked)/(1+xlocked));r={"date":"2026-09-02","gate":SPEC.identifier,"predecessor":"version10_cell_birth_four_volume_nonequilibrium_bath_microscopic_carrier_cutoff_parent_admission_gate","cell_dispersion":{"law":"omega(k)=2*v*sin(k*ell_cell/2)/ell_cell","infrared_group_velocity":"v","cutoff":"Omega_bath=2*v/ell_cell","cell_clock":"Omega_C=c/ell_cell"},"compatibility":{"kappa_over_Omega_C":"k_X=log((1+2*x)/(1+x))","Omega_bath_over_kappa":"121/12","selected_velocity":"v/c=(121/24)*k_X"},"luminal_branch":{"required_k_X":"24/121","selected_x":str(xstar),"selected_S_vac":str(Sstar),"selected_S_vac_decimal":"1.2692505172177279","compatible_with_locked_S_vac":False},"locked_vacuum_branch":{"S_vac":"137.03599917352236","required_v_over_c":str(ulocked),"required_v_over_c_decimal":"1.543266553720361e-59","internal_velocity_origin":False},"scale_orbit":{"rank_nullity":"3/1","kernel":[1,-1,-1,-1]},"candidate_matrix":[list(map(int,c.candidate_matrix.row(i))) for i in range(6)],"candidate_matrix_rank":c.candidate_matrix.rank(),"maximum_score":"5/6","passing_candidates":int(sum(c.pass_vector)),"status":{"conditional_typed_embedding":"9/9","luminal_locked_vacuum_compatibility":"0/1","bath_velocity_origin":"0/1","absolute_scale":"0/1"},"verdict":{"cell_geometry_provides_relative_bath_cutoff":True,"luminal_branch_preserves_locked_vacuum":False,"locked_vacuum_requires_unexplained_ultraslow_bath_velocity":True},"proofdsl":{"status":"lcf-checked","obligation_count":len(v.obligations),"obligations":[n for n,_ in v.obligations],"certificate_sha256":v.sha256,"floating_point_values":0},"next_gate":"version10_cell_birth_four_volume_nonequilibrium_bath_group_velocity_vacuum_growth_common_parent_origin_gate","floating_point_values":0};text=json.dumps(r,ensure_ascii=False,indent=2,sort_keys=True)+"\n";OUT.write_text(text);print(OUT);print(hashlib.sha256(text.encode()).hexdigest());print(v.sha256)
if __name__=="__main__":main()