#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
import sympy as sp
from s2t.proofdsl.examples.version10_cell_birth_four_volume_nonequilibrium_bath_group_velocity_vacuum_growth_common_parent_origin import SPEC,build_certificate
from s2t.proofdsl.gates import verify_gate
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/"s2t/results/s2t_v10_cell_birth_four_volume_nonequilibrium_bath_group_velocity_vacuum_growth_common_parent_origin_gate_results.json"
def main():
 v=verify_gate(SPEC);c=build_certificate();S=sp.Rational(13703599917352236,10**14);x=sp.exp(-S);kx=sp.log((1+2*x)/(1+x));u=sp.Rational(121,24)*kx;r={"date":"2026-09-02","gate":SPEC.identifier,"predecessor":"version10_cell_birth_four_volume_nonequilibrium_bath_continuum_dispersion_cell_geometry_typed_embedding_gate","common_parent":{"functional":"((r-121/12)^2+(q-k_X)^2+(r*q-2*u)^2)/2","variables":["r=Omega_bath/kappa","q=kappa/Omega_C","u=v/c"],"selected_point":{"r":"121/12","q":"k_X","u":"(121/24)*k_X"},"hessian_determinant":4,"hessian_rank":3,"bounded_below":True},"inherited_relations":{"memory_cutoff":"Omega_bath/kappa=121/12","conductance_growth":"kappa/Omega_C=k_X","cell_dispersion":"Omega_bath/Omega_C=2*v/c","provenance_rank":"3/3"},"blind_predictions":{"bath_velocity":"v/c=(121/24)*k_X","bath_to_cell_front_velocity":"121/8","weak_weight_limit":"(v/c)/x -> 121/24"},"locked_vacuum":{"S_vac":"137.03599917352236","v_over_c":str(u),"v_over_c_decimal":"1.543266553720361e-59"},"absolute_scale_orbit":{"rank_nullity":"3/1","kernel":[1,-1,-1,-1]},"status":{"common_parent_architecture":"10/10","conditional_relative_origin":"8/8","dimensionless_velocity_origin":"1/1 conditional","blind_velocity_ratio":"1/1","absolute_scale":"0/1"},"verdict":{"new_free_dimensionless_parameter_introduced":False,"common_parent_selects_bath_velocity_ratio":True,"common_parent_selects_absolute_length_or_time":False},"proofdsl":{"status":"lcf-checked","obligation_count":len(v.obligations),"obligations":[n for n,_ in v.obligations],"certificate_sha256":v.sha256,"floating_point_values":0},"next_gate":"version10_cell_birth_four_volume_nonequilibrium_bath_group_velocity_cell_birth_front_speed_morphism_origin_gate","floating_point_values":0};text=json.dumps(r,ensure_ascii=False,indent=2,sort_keys=True)+"\n";OUT.write_text(text);print(OUT);print(hashlib.sha256(text.encode()).hexdigest());print(v.sha256)
if __name__=="__main__":main()