#!/usr/bin/env python3
import json
from pathlib import Path

import numpy as np


def symmetric_index(dimension):
    return [
        (left, right)
        for left in range(dimension)
        for right in range(left, dimension)
    ]


def diffeomorphism_symbol(momentum):
    dimension = len(momentum)
    indices = symmetric_index(dimension)
    symbol = np.zeros((len(indices), dimension))
    for row, (left, right) in enumerate(indices):
        for column in range(dimension):
            symbol[row, column] = (
                (momentum[left] if right == column else 0.0)
                + (momentum[right] if left == column else 0.0)
            )
    return symbol


def trace_vector(dimension):
    indices = symmetric_index(dimension)
    return np.array(
        [1.0 if left == right else 0.0 for left, right in indices]
    )


def projection_residual(matrix, vector):
    coefficients, *_ = np.linalg.lstsq(matrix, vector, rcond=None)
    residual = vector - matrix @ coefficients
    return float(np.linalg.norm(residual)), coefficients


def main():
    dimension = 4
    metric_dimension = dimension * (dimension + 1) // 2
    majorana_dimension = 24
    trace = trace_vector(dimension)

    zero_symbol = diffeomorphism_symbol(np.zeros(dimension))
    nonzero_symbol = diffeomorphism_symbol(
        np.array([1.0, 0.0, 0.0, 0.0])
    )
    zero_residual, _ = projection_residual(zero_symbol, trace)
    nonzero_residual, nonzero_coefficients = projection_residual(
        nonzero_symbol, trace
    )

    direct_sum_symbol = np.vstack(
        [nonzero_symbol, np.zeros((majorana_dimension, dimension))]
    )
    matter_basis = np.zeros(metric_dimension + majorana_dimension)
    matter_basis[metric_dimension] = 1.0
    matter_residual, _ = projection_residual(
        direct_sum_symbol, matter_basis
    )

    weyl_column = np.concatenate(
        [2.0 * trace, np.zeros(majorana_dimension)]
    ).reshape(-1, 1)
    diffeo_plus_weyl = np.column_stack(
        [direct_sum_symbol, weyl_column]
    )

    defect = json.loads(
        Path("s2t_neutrino_core_gluing_majorana_line_results.json").read_text(
            encoding="utf-8"
        )
    )
    dimension_gate = json.loads(
        Path("s2t_neutrino_majorana_dimension_gate_results.json").read_text(
            encoding="utf-8"
        )
    )

    results = {
        "status": "F3_conformal_mode_does_not_reduce_the_Majorana_module_rank_in_the_minimal_4D_gauge_complex",
        "date": "2026-08-06",
        "linearized_gravity": {
            "spacetime_dimension": dimension,
            "metric_components_per_point": metric_dimension,
            "diffeomorphism_parameters_per_point": dimension,
            "gauge_symbol": "delta h_mn = k_m xi_n + k_n xi_m",
            "constant_mode": {
                "momentum": [0.0] * dimension,
                "gauge_symbol_rank": int(np.linalg.matrix_rank(zero_symbol)),
                "trace_projection_residual_norm": zero_residual,
                "finding": (
                    "A constant volume/conformal mode is not generated by a periodic "
                    "diffeomorphism. Equivalently, the integral of div(xi) vanishes "
                    "on a compact manifold without boundary."
                ),
            },
            "nonzero_mode": {
                "momentum": [1.0, 0.0, 0.0, 0.0],
                "gauge_symbol_rank": int(
                    np.linalg.matrix_rank(nonzero_symbol)
                ),
                "trace_projection_residual_norm": nonzero_residual,
                "least_squares_xi": nonzero_coefficients.tolist(),
                "finding": (
                    "Even at a nonzero Fourier mode the pure trace tensor is not in "
                    "the image of the diffeomorphism symbol. Gauge fixing mixes trace "
                    "and longitudinal components but does not supply a standalone Weyl quotient."
                ),
            },
        },
        "majorana_direct_sum_gate": {
            "field_space": "Sym2(T*K) direct_sum R24_Majorana",
            "diffeomorphism_symbol_rank": int(
                np.linalg.matrix_rank(direct_sum_symbol)
            ),
            "gauge_image_has_Majorana_component": False,
            "test_Majorana_basis_residual_norm": matter_residual,
            "Majorana_rank_before_quotient": majorana_dimension,
            "Majorana_rank_after_gravity_gauge_quotient": majorana_dimension,
            "finding": (
                "Dividing the metric integral by Diff(K) acts in the metric block. "
                "It multiplies the full partition function by a common gauge-volume/ghost "
                "factor and does not delete one vector from the internal Majorana fiber."
            ),
        },
        "weyl_gate": {
            "diffeomorphism_plus_formal_Weyl_rank": int(
                np.linalg.matrix_rank(diffeo_plus_weyl)
            ),
            "formal_Weyl_column": "delta h_mn=2 sigma g_mn",
            "required_for_trace_to_be_gauge": True,
            "present_in_frozen_parent_action": False,
            "matter_consequence": (
                "A Weyl transformation rescales fields by their weights; it does not "
                "select one distinguished real direction inside R24. At the zero-field "
                "background its linear gauge map has no rank-one Majorana image."
            ),
            "wrong_sign_warning": (
                "Rotating the Euclidean conformal-factor contour changes the integration "
                "cycle. It is not a quotient and does not change a finite module dimension."
            ),
        },
        "Ahat_gate": {
            "coefficient": "Ahat=1-p1/24+...",
            "rank_implication": False,
            "finding": (
                "The denominator 24 is the normalization of a characteristic class, "
                "not a count of Majorana components and not evidence for 24-1."
            ),
        },
        "comparison_with_existing_rank_one_routes": {
            "generation_singlet_no_go": dimension_gate["verdict"],
            "defect_rank_one": {
                "combined_real_rank": defect["rank_one_result"][
                    "combined_real_rank"
                ],
                "complement_rank": defect["rank_one_result"][
                    "complement_rank_in_R24"
                ],
                "status": defect["theory_effect"]["full_S2T_status"],
            },
            "finding": (
                "The conformal route fails, but the previously constructed class-D "
                "defect still supplies a conditional one-real-dimensional kernel. "
                "It remains the only explicit route to a rank-23 complement."
            ),
        },
        "no_go": {
            "statement": (
                "In the frozen 4D parent architecture without local Weyl gauge symmetry, "
                "conformal-factor treatment cannot turn R24 into R23. A rank-23 heavy "
                "module requires an operator acting in the Majorana fiber itself."
            ),
            "F3_passes": False,
            "reopening_conditions": [
                "derive an exact local Weyl symmetry of the complete massive parent action",
                "construct its BRST complex and a nonzero mixed gauge map into the Majorana module",
                "prove that the quotient removes exactly one real Majorana direction rather than a common scale or full internal copy",
                "or derive the existing rank-one class-D defect from the S2T action",
            ],
        },
        "scientific_verdict": {
            "negative": (
                "Criterion F.3 closes negatively for the conformal/gauge-volume proposal."
            ),
            "retained": (
                "The conditional topological-defect selector and its internally consistent "
                "R24-to-R23 complement remain available, pending parent-action derivation."
            ),
            "program_effect": (
                "The integer 23 cannot be justified by the Ahat denominator or by removing "
                "the gravitational conformal factor. Its status remains conditional on the "
                "Majorana defect or another explicit rank-one operator."
            ),
        },
    }

    assert metric_dimension == 10
    assert np.linalg.matrix_rank(zero_symbol) == 0
    assert zero_residual == np.linalg.norm(trace)
    assert np.linalg.matrix_rank(nonzero_symbol) == 4
    assert nonzero_residual > 1.0
    assert matter_residual > 0.999999
    assert results["majorana_direct_sum_gate"][
        "Majorana_rank_after_gravity_gauge_quotient"
    ] == 24
    assert defect["rank_one_result"]["combined_real_rank"] == 1
    assert defect["rank_one_result"]["complement_rank_in_R24"] == 23

    Path("s2t_conformal_majorana_rank_gate_results.json").write_text(
        json.dumps(results, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(results, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()