import json
from pathlib import Path

ambient = json.loads(Path("s2t_c6_l21_delta2_ambient_path_formula_results.json").read_text())
decomp = json.loads(Path("s2t_c6_l21_delta2_operator_decomposition_results.json").read_text())

results = {
    "status": "delta2_principal_second_symbol_formula_fixed_matrix_missing",
    "inputs": [
        "s2t_c6_l21_delta2_ambient_path_formula_results.json",
        "s2t_c6_l21_delta2_operator_decomposition_results.json",
    ],
    "operator_convention": {
        "laplacian": "Delta_1 alpha = -g^{ij} nabla_i nabla_j alpha + Ric(alpha)",
        "this_block_only": "principal second-symbol block from the second variation of -g^{ij} partial_i partial_j / -g^{ij} nabla_i nabla_j before connection, Ricci, projector, Hilbert, and local terms",
        "not_included_here": [
            "delta Gamma and delta2 Gamma terms",
            "Ricci/curvature variation",
            "coexact projector variation",
            "Hilbert/basis normalization variation",
            "local counterterm classification",
        ],
    },
    "ambient_metric_path": ambient["selected_path"],
    "metric_derivatives": ambient["metric_derivatives"],
    "inverse_metric_variation_formula": {
        "first": "partial_A g^{ij} = - h_A^{ij}",
        "mixed_second": "partial_A partial_B g^{ij} = h_A^{i}{}_k h_B^{kj} + h_B^{i}{}_k h_A^{kj} - k_{AB}^{ij}",
        "definitions": {
            "h_A": "partial_A g, with h_A(u,v)=2<u,A v>",
            "k_AB": "partial_A partial_B g, with k_AB(u,v)=<A u,B v>+<B u,A v>",
            "raising": "indices are raised with the epsilon=0 round metric on S3/RP3",
        },
    },
    "principal_second_symbol": {
        "mixed_AB": "delta2_principal_AB(Delta_1) alpha = - (partial_A partial_B g^{ij}) nabla_i nabla_j alpha",
        "expanded": "= - (h_A^i_k h_B^{kj} + h_B^i_k h_A^{kj} - k_AB^{ij}) nabla_i nabla_j alpha",
        "same_A": "d2_principal_AA(Delta_1) alpha = - (d2 g^{ij}/d eps^2) nabla_i nabla_j alpha, with d2 g^{-1}=2 h_A^2 - k_AA in raised-index notation",
        "sign_warning": "This is only the principal second-symbol sign. Connection terms generated by differentiating covariant derivatives are separate and can change the full operator contribution.",
    },
    "matrix_task": {
        "required_targets": decomp["target_operator"]["finite_trace_targets"],
        "required_pairs": decomp["finite_block_counts"]["symmetric_deformation_pairs_A_B"],
        "required_raw_diagonal_entries": decomp["finite_block_counts"]["required_diagonal_entries_all_pairs"],
        "status": "not_evaluated",
    },
    "pass_fail": [
        {
            "test": "formula_written",
            "status": "pass",
            "meaning": "The principal second-symbol formula and sign are fixed on the ambient path.",
        },
        {
            "test": "diagonal_matrix_traces_evaluated",
            "status": "not_yet",
            "meaning": "No C_delta2[1,1] or C_delta2[3,3] trace has been computed from this formula.",
        },
        {
            "test": "combined_with_other_delta2_subblocks",
            "status": "not_yet",
            "meaning": "This formula alone cannot decide locality, cancellation, or C6 status.",
        },
    ],
    "plain_language": "One gear of the fifth extinguisher is now shaped: the second inverse-metric piece. It is still sitting on the table; it has not been installed into the full machine.",
    "verdict": "The principal second-symbol part of delta2 Delta_1 is fixed at formula level on the ambient pullback path: delta2_principal_AB = -(partial_A partial_B g^{ij}) nabla_i nabla_j, with partial_A partial_B g^{-1}=h_A h_B+h_B h_A-k_AB. This closes only the formula-level sign gate for one subblock. The diagonal low-shell traces and all non-principal second-order terms remain open.",
}

Path("s2t_c6_l21_delta2_principal_second_symbol_formula_results.json").write_text(json.dumps(results, indent=2, ensure_ascii=False) + "\n")
print(json.dumps({
    "status": results["status"],
    "formula_written": True,
    "matrix_traces_evaluated": False,
    "combined_with_other_subblocks": False,
}, indent=2, ensure_ascii=False))