#!/usr/bin/env python3
import json
from pathlib import Path

import numpy as np


def algebra_dimension(generators):
    dimension = generators[0].shape[0]
    basis = []

    def add(matrix):
        old_dimension = len(basis)
        trial = basis + [matrix]
        rank = np.linalg.matrix_rank(
            np.stack([item.reshape(-1) for item in trial]), tol=1e-10
        )
        if rank > old_dimension:
            basis.append(matrix)
            return True
        return False

    add(np.eye(dimension, dtype=complex))
    for generator in generators:
        add(generator)
    changed = True
    while changed:
        changed = False
        old_basis = list(basis)
        for matrix in old_basis:
            for generator in generators:
                changed = add(matrix @ generator) or changed
    return len(basis)


def commutant_dimension(generators):
    dimension = generators[0].shape[0]
    equations = [
        np.kron(generator.T, np.eye(dimension))
        - np.kron(np.eye(dimension), generator)
        for generator in generators
    ]
    rank = np.linalg.matrix_rank(np.vstack(equations), tol=1e-10)
    return int(dimension * dimension - rank)


def main():
    sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
    sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
    sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)

    multiplicity_two = np.eye(2)
    U4 = np.kron(sigma_x, multiplicity_two)
    V4 = np.kron(sigma_z, multiplicity_two)
    W4 = 1j * U4 @ V4

    coefficient_samples = [
        (0.0, 1.0, 2.0, 3.0),
        (1.0, -2.0, 0.5, 4.0),
        (-0.25, 1.0, -1.0, 0.75),
    ]
    spectral_samples = []
    for a, b, c, d in coefficient_samples:
        hamiltonian = a * np.eye(4) + b * U4 + c * V4 + d * W4
        expected_radius = float(np.sqrt(b * b + c * c + d * d))
        eigenvalues = np.linalg.eigvalsh(hamiltonian)
        spectral_samples.append(
            {
                "coefficients": [a, b, c, d],
                "eigenvalues": eigenvalues.tolist(),
                "expected": [a - expected_radius] * 2
                + [a + expected_radius] * 2,
                "error": float(
                    np.linalg.norm(
                        eigenvalues
                        - np.array(
                            [a - expected_radius] * 2
                            + [a + expected_radius] * 2
                        )
                    )
                ),
            }
        )

    # Six-dimensional realization: the projective doublet times a
    # three-dimensional multiplicity space that one might try to call family.
    multiplicity_three = np.eye(3)
    U6 = np.kron(sigma_x, multiplicity_three)
    V6 = np.kron(sigma_z, multiplicity_three)

    results = {
        "status": "all_minimal_projective_flux_actions_have_even_spectral_multiplicity_and_leave_family_mixing_in_an_unfixed_commutant",
        "date": "2026-08-05",
        "four_state_carrier": {
            "flux_algebra_dimension": algebra_dimension([U4, V4]),
            "flux_commutant_dimension": commutant_dimension([U4, V4]),
            "algebra_form": "M2(C) tensor I2",
            "commutant_form": "I2 tensor M2(C)",
            "canonical_Hermitian_basis": ["I", "U", "V", "iUV"],
            "general_spectrum": "a-r with multiplicity 2 and a+r with multiplicity 2, r=sqrt(b^2+c^2+d^2)",
            "spectral_samples": spectral_samples,
            "possible_spectral_projector_ranks": [0, 2, 4],
            "rank_one_or_rank_three_selector_from_flux_algebra": False,
        },
        "multiplicity_obstruction": {
            "general_representation": "C2_projective tensor C^m_multiplicity",
            "dimension": "2m",
            "flux_algebra": "M2 tensor I_m",
            "commutant": "I2 tensor M_m",
            "consequence": (
                "Every flux-only eigenvalue has multiplicity divisible by m. A rank-one "
                "reference state or a 3+1 split cannot be generated by the flux algebra."
            ),
        },
        "six_state_three_multiplicity_test": {
            "dimension": 6,
            "flux_algebra_dimension": algebra_dimension([U6, V6]),
            "flux_commutant_dimension": commutant_dimension([U6, V6]),
            "algebra_form": "M2 tensor I3",
            "commutant_form": "I2 tensor M3",
            "temptation": "interpret the multiplicity-three factor as three generations",
            "failure": (
                "The flux acts trivially on that factor. All mass hierarchy and mixing "
                "operators then lie in the unrestricted M3 commutant and are not selected by topology."
            ),
        },
        "commutant_breaking_cost": {
            "four_state_case": (
                "Splitting the two equivalent projective copies requires a non-scalar Hermitian "
                "element of M2 in the commutant. Its direction is continuously rotatable by U(2)."
            ),
            "six_state_case": (
                "Producing realistic three-family masses requires a general Hermitian M3 "
                "commutant element; producing CKM requires two noncommuting such elements."
            ),
            "trace_result": (
                "The normalized trace fixes norms after these elements are chosen but does not "
                "select their directions or relative coefficients."
            ),
        },
        "scientific_verdict": {
            "minimal_four_state_flux": (
                "Cannot yield one heavy reference plus three light families because all "
                "flux-only spectral multiplicities are even."
            ),
            "six_state_flux_times_three": (
                "Restores the number three only as an unexplained multiplicity and leaves the "
                "entire flavor problem in an arbitrary M3 commutant."
            ),
            "no_go": (
                "Changing from the 1+3 menu to the minimal projective carrier does not solve "
                "generation counting and mixing simultaneously."
            ),
            "reopening_condition": (
                "An additional discrete symmetry must act irreducibly on the multiplicity space "
                "and fix two noncommuting flavor operators with no continuous coefficients."
            ),
        },
    }

    assert np.linalg.norm(U4 @ U4 - np.eye(4)) < 1e-12
    assert np.linalg.norm(V4 @ V4 - np.eye(4)) < 1e-12
    assert np.linalg.norm(U4 @ V4 + V4 @ U4) < 1e-12
    assert algebra_dimension([U4, V4]) == 4
    assert commutant_dimension([U4, V4]) == 4
    assert all(sample["error"] < 1e-12 for sample in spectral_samples)
    assert algebra_dimension([U6, V6]) == 4
    assert commutant_dimension([U6, V6]) == 9

    Path("s2t_even_projective_carrier_exhaustive_results.json").write_text(
        json.dumps(results, ensure_ascii=False, indent=2) + "\n"
    )
    print(
        json.dumps(
            {
                "status": results["status"],
                "four_state_algebra_dimension": results["four_state_carrier"]["flux_algebra_dimension"],
                "four_state_commutant_dimension": results["four_state_carrier"]["flux_commutant_dimension"],
                "flux_projector_ranks": results["four_state_carrier"]["possible_spectral_projector_ranks"],
                "six_state_commutant_dimension": results["six_state_three_multiplicity_test"]["flux_commutant_dimension"],
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()