import json
import math
from pathlib import Path

from scipy.special import k1


def coexact_modes(n_max):
    """Unit-radius coexact one-form tower on S^3 and RP^3.

    S^3 convention:
        lambda_n=(n+1)^2, d_n=2*n*(n+2), n>=1.

    RP^3=L(2,1) projection:
        The quotient is generated by left multiplication by the central
        element -1 in SU(2). The two transverse one-form families transform
        as ((n+1)/2,(n-1)/2) and ((n-1)/2,(n+1)/2), so the generator acts
        with parity (-1)^(n-1). Hence odd n descend with full S^3
        multiplicity and even n are projected out.
    """
    for n in range(1, n_max + 1):
        degeneracy_s3 = 2 * n * (n + 2)
        yield {
            "n": n,
            "lambda": float((n + 1) ** 2),
            "rho": float(n + 1),
            "rp3_parity": int((-1) ** (n - 1)),
            "degeneracy_s3": float(degeneracy_s3),
            "degeneracy_rp3": float(degeneracy_s3 if n % 2 == 1 else 0),
        }


def bessel_tail_for_rho(rho, q_max, tol):
    total = 0.0
    terms = 0
    for q in range(1, q_max + 1):
        term = k1(2 * math.pi * q * rho) / q
        total += term
        terms = q
        if abs(term) < tol:
            break
    return rho * total, terms


def tower_sum(n_max=80, q_max=1000, tol=1e-18):
    rows = []
    total_s3 = 0.0
    total_rp3 = 0.0
    for mode in coexact_modes(n_max):
        tail, q_terms = bessel_tail_for_rho(mode["rho"], q_max, tol)
        contribution_s3 = mode["degeneracy_s3"] * tail
        contribution_rp3 = mode["degeneracy_rp3"] * tail
        rows.append({
            **mode,
            "rho_bessel_sum": tail,
            "q_terms": q_terms,
            "contribution_s3": contribution_s3,
            "contribution_rp3": contribution_rp3,
        })
        total_s3 += contribution_s3
        total_rp3 += contribution_rp3
    return rows, total_s3, total_rp3


rows, total_s3, total_rp3 = tower_sum()
first_nonzero_rp3 = next(row for row in rows if row["contribution_rp3"] > 0)
results = {
    "status": "rp3_projection_implemented_normalization_still_open",
    "spectrum_convention": {
        "space": "unit-radius coexact one-form tower",
        "lambda_n": "(n+1)^2, n>=1",
        "degeneracy_s3": "2 n (n+2)",
        "rp3_projection": "keep odd n with full S^3 degeneracy; project out even n",
        "degeneracy_rp3": "2 n (n+2) for odd n, 0 for even n",
        "open_normalization": "Overall sign and conversion factor from T_coex to Delta_tower^coex in S_vac remain to be fixed by the determinant normalization.",
    },
    "cutoffs": {"n_max": 80, "q_max": 1000, "term_tol": 1e-18},
    "dimensionless_positive_sum": {
        "s3_full_degeneracy": total_s3,
        "rp3_projected": total_rp3,
        "rp3_over_s3": total_rp3 / total_s3,
        "first_rp3_mode_fraction": first_nonzero_rp3["contribution_rp3"] / total_rp3,
    },
    "first_modes": rows[:12],
}

Path("s2t_coexact_tower_results.json").write_text(
    json.dumps(results, indent=2, ensure_ascii=False) + "\n"
)

print(json.dumps(results["dimensionless_positive_sum"], indent=2))
print("wrote s2t_coexact_tower_results.json")