#!/usr/bin/env python3
import json
import math
from pathlib import Path

import sympy as sp


def main():
    w3, w1, coupling, cosine = sp.symbols(
        "w_3 w_1 g c", real=True
    )
    h = sp.simplify(coupling * (1 - cosine))

    factor_eigenvalues = [2 * w3, 2 * w1, 2 * (w3 + w1)]
    n_plus = sp.Matrix([1, 1, 0]) / sp.sqrt(2)
    n_minus = sp.Matrix([1, -1, 0]) / sp.sqrt(2)
    identity = sp.eye(3)
    factor_operator = sp.diag(*factor_eigenvalues)
    incidence_plus = cosine * identity + (1 - cosine) * (n_plus * n_plus.T)
    incidence_minus = cosine * identity + (1 - cosine) * (n_minus * n_minus.T)
    mass_plus = sp.simplify(factor_operator + coupling * incidence_plus)
    mass_minus = sp.simplify(factor_operator + coupling * incidence_minus)

    third_decouples = all(
        sp.simplify(matrix[index, 2]) == 0
        and sp.simplify(matrix[2, index]) == 0
        for matrix in (mass_plus, mass_minus)
        for index in (0, 1)
    )

    relative_angle_tangent = sp.simplify(h / (2 * (w3 - w1)))
    angle = sp.symbols("theta_mix", real=True)
    crossed_ckm = sp.Matrix(
        [
            [sp.cos(angle), sp.sin(angle), 0],
            [-sp.sin(angle), sp.cos(angle), 0],
            [0, 0, 1],
        ]
    )

    target_cosine = (sp.Integer(26) - 9 * sp.sqrt(15)) / 11
    kernels = {
        "inverse_length": (1 / sp.pi, 1 / (2 * sp.pi)),
        "inverse_square": (1 / sp.pi**2, 1 / (4 * sp.pi**2)),
        "tunneling": (sp.exp(-sp.pi), sp.exp(-2 * sp.pi)),
    }
    sample_couplings = [sp.Rational(1, 10), sp.Rational(1, 2), sp.Integer(1)]
    sensitivity_rows = []
    for name, (weight3, weight1) in kernels.items():
        for sample in sample_couplings:
            tangent = sp.N(
                relative_angle_tangent.subs(
                    {
                        w3: weight3,
                        w1: weight1,
                        coupling: sample,
                        cosine: target_cosine,
                    }
                ),
                16,
            )
            mixing_angle = math.atan(float(tangent))
            sensitivity_rows.append(
                {
                    "kernel": name,
                    "coupling": float(sample),
                    "tan_mixing_angle": float(tangent),
                    "mixing_angle_radians": mixing_angle,
                }
            )

    results = {
        "status": "residual_orbit_reduces_axis_choice_but_minimal_up_down_ansatz_has_one_free_two_family_angle",
        "date": "2026-08-06",
        "character_basis": {
            "translation_eigenvalue_sectors": [
                "(-1,+1)",
                "(+1,-1)",
                "(-1,-1)",
            ],
            "factor_operator": str(factor_operator),
            "selected_projective_axes": {
                "plus": str(n_plus),
                "minus": str(n_minus),
            },
            "axes_use_only_first_two_characters": True,
        },
        "minimal_sector_operators": {
            "ansatz": "M_s=L(w3,w1)+g A_(n_s)",
            "plus_matrix": str(mass_plus),
            "minus_matrix": str(mass_minus),
            "third_character_decouples": third_decouples,
            "aligned_relative_class": {
                "representatives": "n_u=n_d",
                "mixing_matrix": "identity up to signs and permutations",
            },
            "crossed_relative_class": {
                "representatives": "n_u perpendicular to n_d",
                "mixing_matrix": str(crossed_ckm),
                "tan_theta_mix": str(relative_angle_tangent),
                "only_one_real_rotation": True,
                "third_family_unmixed": True,
                "CP_phase": 0,
            },
        },
        "normalization_gate": {
            "free_ratio": "g(1-c)/(2(w3-w1))",
            "factor_geometry_fixes_ratio": False,
            "sample_sensitivity": sensitivity_rows,
            "finding": (
                "The crossed orbit class is discrete, but its mixing angle varies continuously "
                "with the un-derived relative coefficient g. Different admissible factor "
                "kernels also give different angles."
            ),
        },
        "full_M3_warning": {
            "algebraic_result": (
                "The set generated by T_RP3, T_S1, the shear S and A_n can equal M3."
            ),
            "mass_operator_result": (
                "A single linear combination L+g A_n omits the shear and remains block "
                "2+1. Full generated algebra does not by itself specify a physical mass matrix."
            ),
        },
        "scientific_verdict": {
            "positive": (
                "After quotienting by residual symmetry, each sector has one projective axis "
                "orbit and the pair of sectors has only aligned and crossed relative classes."
            ),
            "negative": (
                "The minimal crossed class predicts only a real two-family rotation with a "
                "free angle and no CP phase. It cannot be a parameter-free full CKM derivation."
            ),
            "next_gate": (
                "Derive from one action a noncommuting shear or second incidence term with fixed "
                "coefficient and a complex orientation, then recompute masses and mixing before "
                "using quark data."
            ),
        },
    }

    assert third_decouples
    assert sp.simplify(incidence_plus[2, 2] - cosine) == 0
    assert sp.simplify(incidence_minus[2, 2] - cosine) == 0
    assert sp.trigsimp(crossed_ckm.det()) == 1

    Path("s2t_family_relative_orbit_ckm_results.json").write_text(
        json.dumps(results, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(
        json.dumps(
            {
                "status": results["status"],
                "third_character_decouples": third_decouples,
                "relative_classes": ["aligned", "crossed"],
                "tan_theta_mix": str(relative_angle_tangent),
                "free_relative_coefficient": True,
                "full_CKM": False,
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()