import json
from pathlib import Path

ambient = json.loads(Path("s2t_c6_l21_delta2_ambient_path_formula_results.json").read_text())
connection1 = json.loads(Path("s2t_c6_l21_connection_variation_formula_results.json").read_text())
decomp = json.loads(Path("s2t_c6_l21_delta2_operator_decomposition_results.json").read_text())

results = {
    "status": "delta2_second_connection_formula_skeleton_fixed_delta2Gamma_expansion_missing",
    "inputs": [
        "s2t_c6_l21_delta2_ambient_path_formula_results.json",
        "s2t_c6_l21_connection_variation_formula_results.json",
        "s2t_c6_l21_delta2_operator_decomposition_results.json",
    ],
    "operator_convention": {
        "laplacian": "Delta_1 alpha = -g^{ij} nabla_i nabla_j alpha + Ric(alpha)",
        "this_block_only": "second-connection part generated by varying covariant derivatives in the rough one-form Laplacian",
        "not_included_here": [
            "principal second-symbol inverse-metric block already fixed separately",
            "Ricci/curvature second variation",
            "coexact projector second variation",
            "Hilbert/basis second variation",
            "local counterterm classifier",
        ],
    },
    "ambient_metric_path": ambient["selected_path"],
    "metric_derivatives": ambient["metric_derivatives"],
    "first_connection_reference": connection1["connection_variation_formula"],
    "connection_variation_formulas": {
        "first_general": "delta_A Gamma^k_ij = 1/2 g^{k l}(nabla_i h^A_jl + nabla_j h^A_il - nabla_l h^A_ij)",
        "second_mixed_skeleton": "delta2_AB Gamma^k_ij = variation_B[delta_A Gamma^k_ij] using partial_B g^{-1}, partial_B h_A, and connection variation inside covariant derivatives, plus A<->B symmetrization",
        "expanded_obligation": [
            "inverse-metric part: (partial_B g^{kl})(nabla_i h^A_jl+nabla_j h^A_il-nabla_l h^A_ij) plus A<->B",
            "metric-second-derivative part: g^{kl}(nabla_i k_AB_jl+nabla_j k_AB_il-nabla_l k_AB_ij)",
            "covariant-derivative variation part: g^{kl} delta_B[nabla h_A] plus A<->B, containing delta Gamma_B * h_A terms",
            "symmetrize in A,B and keep the same ambient pullback path convention",
        ],
        "warning": "This audit fixes the skeleton and required expansion terms, not the fully expanded tensor polynomial on S3/RP3.",
    },
    "rough_laplacian_connection_slots": {
        "one_form_first_derivative": "delta(nabla_i alpha_j) = - delta Gamma^k_ij alpha_k",
        "second_derivative_connection_skeleton": [
            "delta2(nabla_i nabla_j alpha_c) contains -delta2 Gamma^m_ij nabla_m alpha_c",
            "delta2(nabla_i nabla_j alpha_c) contains -delta2 Gamma^m_ic nabla_j alpha_m",
            "products delta Gamma_A delta Gamma_B acting on alpha and nabla alpha",
            "derivatives nabla(delta2 Gamma_AB) and nabla(delta Gamma_A delta Gamma_B) after expanding covariant derivatives",
        ],
        "principal_exclusion": "Terms where only partial_A partial_B g^{ij} multiplies nabla_i nabla_j alpha are assigned to principal_second_symbol, not this block.",
    },
    "matrix_task": {
        "required_targets": decomp["target_operator"]["finite_trace_targets"],
        "required_pairs": decomp["finite_block_counts"]["symmetric_deformation_pairs_A_B"],
        "required_raw_diagonal_entries": decomp["finite_block_counts"]["required_diagonal_entries_all_pairs"],
        "status": "not_evaluated",
    },
    "pass_fail": [
        {
            "test": "formula_skeleton_written",
            "status": "pass",
            "meaning": "The second-connection terms are now located and separated from the principal second-symbol block.",
        },
        {
            "test": "delta2Gamma_fully_expanded",
            "status": "not_yet",
            "meaning": "The complete ambient-path tensor expression for delta2 Gamma_AB is still missing.",
        },
        {
            "test": "diagonal_matrix_traces_evaluated",
            "status": "not_yet",
            "meaning": "No diagonal C_delta2 traces have been computed from the second-connection block.",
        },
    ],
    "plain_language": "The second gear is now located: it is all the ways the connection itself accelerates and multiplies itself. We know where it sits, but the gear teeth are not cut yet.",
    "verdict": "The second-connection subblock is now fixed at skeleton level. It consists of delta2 Gamma_AB terms, inverse-metric times first-connection variation terms, covariant-derivative variation of h_A, and products delta Gamma_A delta Gamma_B inside the rough one-form Laplacian. This is not yet a complete tensor expansion or a matrix computation; diagonal C_delta2 traces remain open.",
}

Path("s2t_c6_l21_delta2_second_connection_formula_results.json").write_text(json.dumps(results, indent=2, ensure_ascii=False) + "\n")
print(json.dumps({
    "status": results["status"],
    "formula_skeleton_written": True,
    "delta2Gamma_fully_expanded": False,
    "matrix_traces_evaluated": False,
}, indent=2, ensure_ascii=False))